"""Mesh writing / normalization (pure stdlib).

Writes Wavefront OBJ, which every DCC tool, ROS, and three.js can read.
For textured assets from TRELLIS/Nerfstudio you will typically carry GLB;
``copy_or_convert`` passes those through untouched and only synthesizes OBJ
for the procedural path.
"""

from __future__ import annotations

import os
import shutil


def write_box_obj(path: str, dimensions_m: tuple[float, float, float]) -> None:
    """Write an axis-aligned box centered on its base, +Y up.

    The origin sits at the center of the bottom face so the URDF places the
    object *on* a surface, which is what you want for a real-world item.
    """
    w, h, d = dimensions_m
    hx, hz = w / 2.0, d / 2.0
    # 8 corners: y from 0 (base) to h (top).
    verts = [
        (-hx, 0.0, -hz), (hx, 0.0, -hz), (hx, 0.0, hz), (-hx, 0.0, hz),
        (-hx, h, -hz), (hx, h, -hz), (hx, h, hz), (-hx, h, hz),
    ]
    # Faces as quads (1-indexed in OBJ), CCW outward.
    faces = [
        (1, 2, 3, 4),  # bottom
        (5, 8, 7, 6),  # top
        (1, 5, 6, 2),  # -z
        (2, 6, 7, 3),  # +x
        (3, 7, 8, 4),  # +z
        (4, 8, 5, 1),  # -x
    ]
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w") as fh:
        fh.write("# generated by assetpipe (procedural_box)\n")
        for x, y, z in verts:
            fh.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for f in faces:
            fh.write("f " + " ".join(str(i) for i in f) + "\n")


def copy_or_convert(src: str, dst: str) -> None:
    """Place a reconstructed mesh into the asset folder.

    OBJ/GLB/PLY are copied as-is (keep the destination extension in sync
    with the source when it is not OBJ). Real format conversion (e.g. GLB
    -> OBJ) belongs to trimesh/assimp and is out of scope for the stdlib
    slice.
    """
    if not os.path.exists(src):
        raise FileNotFoundError(src)
    ext = os.path.splitext(src)[1].lower()
    if ext != ".obj":
        dst = os.path.splitext(dst)[0] + ext
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    if os.path.abspath(src) != os.path.abspath(dst):
        shutil.copyfile(src, dst)
